workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENVIRONMENT: 'prod'
        S3_BUCKET: $S3_BUCKET_PROD
        CLOUDFRONT_DIST_ID: $CLOUDFRONT_DIST_ID_PROD
        NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL_PROD
    - if: $CI_COMMIT_BRANCH == "preprod"
      variables:
        ENVIRONMENT: 'preprod'
        S3_BUCKET: $S3_BUCKET_PREPROD
        CLOUDFRONT_DIST_ID: $CLOUDFRONT_DIST_ID_PREPROD
        NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL_PREPROD
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:
        ENVIRONMENT: 'dev'
        S3_BUCKET: $S3_BUCKET_DEV
        CLOUDFRONT_DIST_ID: $CLOUDFRONT_DIST_ID_DEV
        NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL_DEV

stages:
  - build
  - deploy
  - redeploy
  - syntax-check

syntax-check:
  stage: syntax-check
  image: node:22.21.1-alpine
  before_script:
    - echo "🔍 Running syntax checks for $ENVIRONMENT environment"
    - npm install -g pnpm
  script:
    - pnpm install --no-strict-peer-dependencies
    - pnpm lint
    - pnpm prettier-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "preprod"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always

node-build:
  stage: build
  image: node:22.21.1-alpine
  before_script:
    - echo "🚀 Building for $ENVIRONMENT environment"
    - apk add --no-cache figlet
    - figlet "Fiyuu Partners Build"
    - npm install -g pnpm
    - |
      cat > .env.$ENVIRONMENT << EOF
      NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
      EOF
  script:
    - pnpm install --no-strict-peer-dependencies
    - pnpm install env-cmd --save-dev
    - |
      if [ "$ENVIRONMENT" = "prod" ]; then
        pnpm build
      elif [ "$ENVIRONMENT" = "preprod" ]; then
        pnpm build:preprod
      else
        pnpm build:dev
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - when: manual
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  image: node:22.21.1-alpine
  before_script:
    - apk update
    - apk add --no-cache aws-cli
    - aws --version
  script:
    - aws s3 sync out/ $S3_BUCKET
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "preprod"'
      when: manual
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: manual
# rollback:
#   stage: redeploy
#   image: node:16.1.0-alpine
#   before_script:
#     - apk update
#     - apk add --no-cache aws-cli
#     - aws --version
#   script:
#     - aws s3 cp dist/index.html $S3_BUCKET/index.html
#     - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
#   rules:
#     - when: manual
