namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_BASE_URL: string
    NEXT_PUBLIC_TURNSTILE_SITEKEY: string
    NEXT_PUBLIC_TURNSTILE_ACTIVE: string
    NEXT_PUBLIC_POSTHOG_KEY: string
    NEXT_PUBLIC_POSTHOG_HOST: string
    NEXT_PUBLIC_INSTANA_REPORTING_URL: string
    NEXT_PUBLIC_INSTANA_KEY: string
    NEXT_PUBLIC_INSTANA_EUM_SRC: string
    NEXT_PUBLIC_INSTANA_EUM_INTEGRITY: string
    NEXT_PUBLIC_APP_VERSION: string
  }
}
