export { default as Motorcycle } from './duel-tone/courier-motorcycle.svg'
export { default as CourierVector } from './duel-tone/courier-vector.svg'
export { default as DeliveryCheckList } from './duel-tone/fiyuu-icon-set/Delivery, Check, List.svg'
export { default as DeliveryShipmentPackagesAdd } from './duel-tone/fiyuu-icon-set/Delivery, Shipment, Packages, Add.svg'
export { default as SiteLogoBig } from './duel-tone/logo-big.svg'
export { default as SiteLogoMin } from './duel-tone/logo-min.svg'
